#JDBC Configutation for Database Connection
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://vprofile-rearchi.cev44i0my55e.us-east-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=AjfGjBq1fyxsMK5WZFTv

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=vprofile-rearchi.apgsyw.cfg.use1.cache.amazonaws.com  
memcached.active.port=11211
#For StandBy Host
memcached.standBy.host=127.0.0.1
memcached.standBy.port=11211

#RabbitMq Configuration
rabbitmq.address=b-29a9e19a-84e3-4fb4-a674-3f9790139454.mq.us-east-1.on.aws
rabbitmq.port=567
rabbitmq.username=rabit
rabbitmq.password=Nmitise@2027

#Elasticesearch Configuration
elasticsearch.host =192.168.1.85
elasticsearch.port =9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
